mytestsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# ===== add
# from {appname} import views


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('poems/', include('poems.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('', RedirectView.as_view(url='/poems/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

poems/urls.py
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url

from . import views, views_archiv

app_name = 'poems'

#POEM_GUSKOV

urlpatterns = [
    # path('eng', views.index_eng, name='index_eng'),
    path('', views.index, name='index'),

    # path('authors/', views.author_list, name='authors'),
    path('authors/ukr', views.author_list_ukr, name='authors_ukr'),
    path('authors/<pk>', views.AuthorDetailView.as_view(), name='author-detail'),

    # path(r'^genres/$', views.GenreListView.as_view(), name='genres'),
    # path('genres/', views.genre_list, name='genres'),
    path('genres/ukr', views.genre_list_ukr, name='genres_ukr'),
    # path(r'^genres/(?P<pk>\d+)$', views.GenreDetailView.as_view(), name='genre-detail'),
    path('genres/<pk>', views.genre_detail, name='genre-detail'),
    path('image/', views.genre_image_list, name='genre_image'),

    path('books/ukr', views.book_list, name='books'),
    # path('book/<pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<pk>', views.book_detail, name='book-detail'),

    # path(r'^poems/$', views.PoemListView.as_view(), name='poem'),
    path('poems/', views.poem_list_all, name='poem_tytle'),
    path('poems/ukr', views.poem_list_ukr, name='poem_tytle_ukr'),
    path('poems/rus', views.poem_list_rus, name='poem_tytle_rus'),

    path('poems/str/', views.poem_list_string_all, name='poem_string'),
    path('poems/str/ukr', views.poem_list_string_ukr, name='poem_string_ukr'),
    path('poems/str/rus', views.poem_list_string_rus, name='poem_string_rus'),

    # path('poems/<pk>', views.PoemDetailView.as_view(), name='poem-detail'),
    path('poems/<pk>', views.poem_detail, name='poem-detail'),
    path('genre/<poem_pk>/<genre_id>', views.poem_detail_genre, name='poem-genre'),
    path('book/<poem_pk>/<book_id>', views.poem_detail_book, name='poem-book'),
    path('lang/<poem_pk>/<lang>', views.poem_detail_lang, name='poem-lang'),

    path('collage/', views.collage_list, name='poem-collage-list'),
    path('collage/<pk>', views.collage_poem, name='poem-collage'),

]
urlpatterns += [

]

urlpatterns += [

    path('', RedirectView.as_view(url='/poems/', permanent=True)), #from M-django
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #from M-django

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # example: /polls/
    path('', views.index, name='index'),

    path('<int:question_id>/', views.detail, name='detail'),

    path('<int:question_id>/results/', views.results, name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

poems/models.py
from django.db import models
from django.urls import reverse
import datetime
import uuid  # Required for unique book instances

#POEM_GUSKOV

# =========================== LANGUAGE ========================
class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name





# ================ Author ===============================
class Author(models.Model):
    class Meta:
        ordering = ["last_name"]
    # author = models.CharField(default="Гуськов", max_length=25)
    first_name = models.CharField(null=True, blank = True, max_length=25)
    middl_name = models.CharField(null=True, blank = True, max_length=25)
    last_name = models.CharField(max_length=45)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=25, null=True, blank = True)


    # date_of_death = models.DateField('Died', null=True, blank=True)
    # def full_name(self):
    #     return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('poems:author-detail', args=[str(self.id)])

    def __str__(self):
        return (self.last_name+ " " + self.first_name)
    # def get_absolute_url(self):
    #     return reverse('author-detail', args=[str(self.id)])


# ================ Genre ===============================
class Genre(models.Model):
    class Meta:
        ordering = ["name"]
    name = models.CharField(max_length=30,
                            help_text="Enter a book genre (e.g. Бог, Війна, Любов etc.)")
    image_genre = models.CharField(max_length=100, null = True, blank = True)
    image_name = models.CharField(max_length=100, null = True, blank = True)
    genre_text_color = models.CharField(max_length=30, default = 'bwbw')


    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('poems:genre-detail', args=[str(self.id)])


# ================ BOOK ===============================
class Book(models.Model):
    class Meta:
        ordering = ["-public_date"]
    public_date = models.DateField(null = True , blank = True)
    name_book = models.CharField(null=True, max_length=20)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    author_status = models.CharField(null=True, blank = True, max_length=30)
    summary = models.TextField(null=True, blank = True, max_length=1000, help_text="Enter a brief description")
    isbn = models.CharField(default='ISBN', max_length=17, help_text='17 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    pages = models.IntegerField(default=0)
    poems_count = models.IntegerField(default=0)
    image_book = models.CharField(max_length=100, null = True , blank = True)

    def __str__(self):
        return str(str.upper(self.title))

    def get_absolute_url(self):
        return reverse('poems:book-detail', args=[str(self.id)])


# ================ Poem ===============================
class Poem(models.Model):
    class Meta:
        ordering = ["tytle"]
    date = models.DateField(null = True, blank = True, )
    author = models.ForeignKey(Author, on_delete=models.SET_NULL,
                               null = True, blank=True)
    tytle = models.CharField(default=" ", max_length=100)
    poem_lang = models.CharField(default="укр.", max_length=4)
    headline = models.CharField(max_length=200)
    content = models.TextField()
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this poem")
    book = models.ManyToManyField(Book, help_text="Enter books, where ware this poem")
    summary = models.TextField(blank = True, max_length=1000,
                               default="", help_text="Enter a poem description")
    image_poem = models.CharField(max_length=100, null = True , blank = True)

    def __str__(self):
        return str(self.tytle)

    def get_absolute_url(self):
        return reverse('poems:poem-detail', args=[str(self.id)])

#===========================================python manage.py migratepython manage.py migratepython manage.py migrate

poems/views.py
from django.shortcuts import render
#render - функция, которая генерирует HTML-файлы
# при помощи шаблонов страниц и соответствующих данных.

# Create your views here.
from django.template import loader
from django.http import HttpResponse
from django.http import Http404
from django.views import generic
from django.db.models import Q

from . models import Author, Genre, Book, Poem
# D:\\web\\dj\\mytestsite\\poems\\


# ================================ poem_context ==================
poem_context_art = "1"
poem_context_name = "2"
poem_context_list = []


# ================== INDEX UKR MDN Web Docs part 5 ===========================
def index(request):
    # Функция отображения для домашней страницы сайта.
    # Генерация "количеств" некоторых главных объектов

    num_genres = Genre.objects.all().count()
    num_books  = Book.objects.all().count()
    num_poems_guskov = Poem.objects.all().filter(author = 1).count()
    num_authors = Author.objects.all().count() + 1
    num_poems_authors = Poem.objects.all().count() - num_poems_guskov
    num_collage = Poem.objects.filter(image_poem__contains = "collage").count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    name_tytle = "Бібліотека поезій Анатолія Гуськова"
    name_text = "Поетична бібліотека містить:"
    name_book = "Книг"
    name_genre = "Жанрів"
    name_poems_guskov = "Віршів А. Гуськова"
    name_authors = "Інших авторів"
    name_poems_authors = "Віршів інших авторів"
    name_collage = "Віршів з колажами"

    # Отрисовка HTML-шаблона index.html с данными
    # внутри переменной контекста context
    return render(
        request, 'poems/index.html',
        context={'num_genres': num_genres,
                 'num_poems_guskov': num_poems_guskov,
                 'num_poems_authors': num_poems_authors, 'num_authors': num_authors,
                 'num_books': num_books, 'num_visits': num_visits,
                 'name_tytle': name_tytle, 'name_text': name_text, 'name_authors': name_authors,
                 'name_book': name_book, 'name_genre': name_genre,
                 'name_poems_guskov': name_poems_guskov, 'name_poems_authors': name_poems_authors,
                 'name_collage': name_collage, 'num_collage': num_collage,
                }
    )

# =======================  AUTHOR LIST UKR ================
def author_list_ukr(request):
    author_list = Author.objects.all().filter(~Q(id=1))
    num_authors = Author.objects.all().filter(~Q(id=1)).count()
    num_poems = Poem.objects.all().filter(~Q(author_id=1)).count()

    name_tytle = "Автори Поезії війни"
    name_authors = "Усього авторів:"
    name_poems = "віршів:"
    name_library = "Бібліотека поезій Анатолія Гуськова"
    name_poem_list = "Обири автора, щоб побачити його вірші"

    return render(
        request,
        'poems/author_list.html',
        context={'author_list': author_list, 'num_authors': num_authors,
                 'name_tytle': name_tytle, 'name_authors': name_authors,
                 'name_poems': name_poems, 'num_poems': num_poems,
                 'name_library': name_library, 'name_poem_list': name_poem_list }
    )

# ===============================
class AuthorDetailView(generic.DetailView):
    model = Author

# =============== GENRE Пользовательское представление ================

def genre_list_ukr(request):
    genre_list = Genre.objects.all()

    name_tytle = "Перелік жанрів"
    name_text = "Усьго жанрів:"
    name_poem = "віршів:"
    name_library = "Бібліотека поезій Анатолія Гуськова"

    return render(
        request,
        'poems/genre_list.html',
        context={'genre_list': genre_list,
                 'name_tytle': name_tytle, 'name_text': name_text,
                 'name_poem': name_poem, 'name_library': name_library }
    )

#======================================
def genre_detail(request, pk):

    genre_id = Genre.objects.get(pk=pk)
    name_tytle = "Перелік жанрів"
    name_genre_text = "У цьому жанрі віршів:"
    name_poem = "віршів:"
    name_library = "Бібліотека поезій Анатолія Гуськова"
    color1 = genre_id.genre_text_color[0]
    color2 = genre_id.genre_text_color[1]
    color3 = genre_id.genre_text_color[2]
    color4 = genre_id.genre_text_color[3]

    return render(
        request,
        'poems/genre_detail.html',
        context={'genre': genre_id,
                 'name_tytle': name_tytle, 'name_genre_text': name_genre_text,
                 'name_poem': name_poem, 'name_library': name_library,
                 'color1': color1, 'color2': color2, 'color3': color3, 'color4': color4,
                 }
    )

#==================== genre_image_lst ===========
def genre_image_list(request):

    genre_image_list = Genre.objects.all().order_by('image_name')

    image_list = \
        [{"image_genre": "images/authors_from Bakla.png", "image_name": "гора Чатир-Даг"},
         {"image_genre": "images/poems_from_Tepe.png", "image_name": "гори з Тепе-Кермену"},
         {"image_genre": "images/genre_from_Chufut.png", "image_name": "плато Бурунчак"},
         {"image_genre": "images/books_from Bakla.png", "image_name": "ранок на Баклі"},
         {"image_genre": "images/index_from_Bakla.png", "image_name": "долини навколо Бакли"},
         {"image_genre": "images/collage_from_Kacha.png", "image_name": "долина Качі, скала Фицкі"},
         ]
    for i in range (len(genre_image_list)):
        image_list.append({"image_genre": genre_image_list[i].image_genre,
                           "image_name": genre_image_list[i].image_name})

    # image_list.sort("image_name")
    num_image = len(image_list)

    return render(
        request,
        'poems/genre_image_list.html',
        context={'image_list': image_list,
                 'num_image': num_image,

                  }
    )

#================= BOOK Пользовательское представление =================
#=============== book_list_ukr =======================
def book_list(request):
    book_list = Book.objects.all().order_by("-public_date")

    name_tytle = "Перелік Книг"
    name_text = "Усього книг:"
    name_from = "із"
    name_poem = "віршів"
    name_library = "Бібліотека поезій Анатолія Гуськова"

    return render(
        request,
        'poems/book_list.html',
        context={'book_list': book_list,
                 'name_tytle': name_tytle, 'name_text': name_text,
                 'name_library': name_library, 'name_from': name_from,
                 'name_poem': name_poem}
    )

#=============== book_detail_ukr =======================
def book_detail (request, pk):
    book = Book.objects.get(pk=pk)

    return render(
        request,
        'poems/book_detail.html',
        context={'book': book,

                 }
    )

# ================ POEMS LIST TITLE =====================================
def poem_list_all(request):
    poem_list = Poem.objects.all().filter(author_id = 1)
    poem_list_authors = Poem.objects.all().filter(~Q(author_id = 1))

    name_tytle_poem = "Перелік Віршів"
    name_num = "Усього віршів"
    name_num_poems = "Вірші А. Гуськова"
    name_library = "Бібліотека поезій Анатолія Гуськова"
    name_num_poems_authors = "Вірші інших авторів"

    return render(
        request,
        'poems/poem_list.html',
        context={'poem_list_guskov': poem_list, 'poem_list_authors': poem_list_authors,
                 'num_guskov': len(poem_list), 'num_authors': len(poem_list_authors),
                 'num': len(poem_list) + len(poem_list_authors),
                 'name_tytle_poem': name_tytle_poem, 'name_num_poems': name_num_poems,
                 'name_num_poems_authors': name_num_poems_authors,
                 'name_library': name_library, 'name_num': name_num,
                 }
    )

# =============================== poem_list_ukr
def poem_list_ukr(request):
    poem_list = Poem.objects.all().filter(author_id=1, poem_lang = 'укр.')
    poem_list_authors = Poem.objects.all().filter(~Q(author_id=1),poem_lang = 'укр.')

    name_tytle_poem = "Вірші українською"
    name_library = "Бібліотека поезій Анатолія Гуськова"
    name_num = "Усього віршів"
    name_num_poems = "Вірші А. Гуськова"
    name_num_poems_authors = "Вірші інших авторів"

    return render(
        request,
        'poems/poem_list.html',
        context={'poem_list_guskov': poem_list, 'poem_list_authors': poem_list_authors,
                 'num_guskov': len(poem_list), 'num_authors': len(poem_list_authors),
                 'num': len(poem_list) + len(poem_list_authors),
                 'name_tytle_poem': name_tytle_poem, 'name_num_poems': name_num_poems,
                 'name_num_poems_authors': name_num_poems_authors,
                 'name_library': name_library, 'name_num': name_num,
                 }
    )

# =============================== poem_list_rus
def poem_list_rus(request):
    poem_list = Poem.objects.all().filter(author_id=1, poem_lang='рос.')
    poem_list_authors = Poem.objects.all().filter(~Q(author_id=1), poem_lang='рос.')

    name_tytle_poem = "Вірші російською"
    name_library = "Бібліотека поезій Анатолія Гуськова"
    name_num = "Усього віршів"
    name_num_poems = "Вірші А. Гуськова"
    name_num_poems_authors = "Вірші інших авторів"

    return render(
        request,
        'poems/poem_list.html',
        context={'poem_list_guskov': poem_list, 'poem_list_authors': poem_list_authors,
                 'num_guskov': len(poem_list), 'num_authors': len(poem_list_authors),
                 'num': len(poem_list) + len(poem_list_authors),
                 'name_tytle_poem': name_tytle_poem, 'name_num_poems': name_num_poems,
                 'name_num_poems_authors': name_num_poems_authors,
                 'name_library': name_library, 'name_num': name_num,
                 }
    )

# ============================== POEMS LIST STRING =====+++++==========
def poem_list_string_all(request):

polls/templates/poems/base_generic.html
<!--POLLS TEMPLATE POEMS-->

<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Title</title>{% endblock %}

    <meta charset="utf-8">
    <!-- Responsibilaty -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Сompiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Сompiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>

    .side_left {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:1.1%;       top:0%;
        width: 14.36%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }
    .side_right {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:84.0%;       top:0px;
        width: 14.36%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }
    .content {
        background: rgb(210, 250, 240);
        border: 0px solid black;
        position: absolute;
        left:16.50%;       top:0px;
        width: 66.49%;   height: 98.0%;
        padding-left: 20;
        list-style: none;
    }
    .menu {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:8.0%;       top:4.0%;
        width: 80%;   height:;
        padding-left: 0;
        list-style: none;
    }
    .menu_ukr {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:8.0%;       top:0.0%;
        width: 80%;   height:;
        padding-left: 0;
        list-style: none;
    }
    .copy_right {
        border: 0px solid black;
        position: absolute;
        left:8.0%;       top:86.0%;
    }

    </style>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles_poem.css' %}">

</head>

<body>
<!--<div class="container-fluid">-->
      {% block sidebar %}
<div class="side_left">

      <img src="{% static 'images/panel_left.png' %}" alt="Chatyrdag_left"
                 style="width:100%;height:100%;"/>

      <div class="menu_ukr">
           <h5 style ="color: blue;"><b>Головне меню</b></h5>

          <li><a href="{% url 'poems:index' %}"><strong>Домашня</strong></a></li>
          <li><a href="{% url 'poems:books' %}"><strong>Всі Книги</strong></a></li>
          <li><a href="{% url 'poems:genres_ukr' %}"><strong>Всі Жанри</strong></a></li>
          <li><a href="{% url 'poems:poem_tytle' %}"><strong>Вірші Назви</strong></a></li>
          <li><a href="{% url 'poems:poem_string' %}"><strong>Вірші Строки</strong></a></li>
          <li><a href="{% url 'poems:authors_ukr' %}"><strong>Інші Автори</strong></a></li>
          <li><a href="{% url 'poems:genre_image' %}"><strong>Фотоархів</strong></a></li>
          <li><a href="{% url 'poems:poem-collage-list' %}"><strong>Колажі віршів</strong>
                                  <b style= "color: red">&{{symbol_collage}};</b></a></li>

    </div>  <!-- menu_ukr -->

      <div class="copy_right">

          <p style="line-height: 50%; font-size: 12px; color: white">
              <b> &#169 Anatoliy Guskov </b> </p>
          <p style="line-height: 50%; font-size: 11px; color: white">
              &nbsp;&nbsp;&nbsp;&nbsp;Version: Mai 2022  </p>
          <p style="line-height: 50%; font-size: 11px; color: white">
              &nbsp;&nbsp;&nbsp;&nbsp;dkgb@i.ua </p>
          <p style="line-height: 50%; font-size: 11px; color: white">
             &nbsp;&nbsp;&nbsp;&nbsp;+380 97 760 4885 </p>
      </div>  <!-- copy_right  -->


</div> <!-- side_left -->

<div class="side_right">
    <img src="{% static 'images/panel_right.png' %}" alt="Chatyrdag_right"
                 style="width:100%;height:100%;"/>

</div> <!-- side_right -->

 {% endblock %} <!-- sidebar -->

      <div class="content">
      {% block content %}

      {% endblock %}
      </div>  <!-- content -->


<!--</div>  &lt;!&ndash; container-fluid &ndash;&gt;-->

</body>

</html>

polls/templates/poems/genre_list_poem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
    table, th, td {
      border:0px solid black;
    }

    #top-left {
    position: absolute;
    top: 0px;
    left: 40px;
    }

    </style>
    <meta charset="UTF-8">
    <title>Genre List</title>

</head>
<body>

{% extends "poems/base_generic.html" %}
{% load static %}

{% block content %}

<img src="{% static 'images/genre_from_Chufut.png' %}" alt="From Chufut"
     style="width:700px;height:210px;"/>

    <h1>Genre List</h1>

    {% if genre_list_poem %}
    <ul>

      <p>There {% if genre_num == 1 %} is {{ gehre_num }} genre:
               {% else %} are {{ genre_num }} genres: {% endif %}</p>

      {% for genre in genre_list_poem %}
<table style="width: 140px">
<tr>
          <td style="width:125px"><a href="{{ genre.get_absolute_url }}">  <b> {{ genre.name }} </b> </a> </td>
          <td align="right">  {% if genre.poem_num > 0 %} {{ genre.poem_num }} {% endif %} </td>
</tr>
</table>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no genres in the library.</p>
    {% endif %}
{% endblock %}

</body>
</html>

polls/templates/poems/poem_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poem Detail</title>

    <style>
    .poem_tytle {
        border:0px solid blue;
        border-radius: 10px;
        background: rgb(210, 220, 240);
        position: absolute;
        left:2px;       top:2px;    bottom: 2px;
        width: 63%;     height: 99%;
        padding-left: 10px; padding-right: 10px;
        color: blue;
    }

    .poem_text {
        overflow: auto;
        border-radius: 10px;
        background: rgb(210, 250, 240);
           left:0px;       top:8.0%;
           width: 100%;    height: 86.0%;
        padding-left: 0px; padding-right: 0px;
        padding-top: 0px;
    }

    .poem_detail {
        border:0px solid blue;
        border-radius: 10px;
        background: rgb(210, 220, 240);
        position: absolute;
        left:65%;       top:2px;
        width: 34%;     height:;
        padding-left: 10px; padding-right: 5px;
        padding-top: 15px;
    }

    p1 {
          line-height: 0.5; font-size: 12px
    }

    pre1 {
        overflow: none;
        background-color: none;
        font-size: 12px
    }

    .side_right_tytle {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:102.5%;       top:1.0%;
        width: 20.2%;   height: 31.5%;
        padding-left: 0;
        color: blue;
    }

    .side_right_poem {
        background: none;
        border: 0px solid white;
        overflow: auto;
        position: absolute;
        left:102.5%;       top: 32.0%;
        width: 20.5%;   height: 67.0%;
        padding-left: 0;
        color: blue;
    }


    </style>
    {% extends "poems/base_generic.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles_poem.css' %}">

</head>
<body>

{% block content %}

<div class="poem_tytle">
    {% block poem %}
  <h3>&nbsp;&nbsp;{{ poem.tytle }}</h3>
<div class = "poem_text"> <!-- Блок текста стихотворения  -->
   <pre style="font-family:Georgia,serif; font-size: 16px">{{ poem.content }}</pre>
</div> <!-- poem_text -->
    {% endblock %}
</div> <!-- poem_tytle -->


<div class = "poem_detail"> <!-- Блок информации о стихотворении  -->
    {% block poem_detail %}
  <p1 style="font-size: 10">{{ poem.date }}</p1>

  {% if poem.author.last_name == "Гуськов" %}
  <h5> <b>{{poem.author.last_name}} {{poem.author.first_name}}</b> </h5>
  {% else %}
  <h5> <a href="{% url 'poems:author-detail' poem.author.pk %}">
      <b>{{poem.author.last_name}} {{poem.author.first_name}}</b> </a> </h5>
  {% endif %}

  <p  style="white-space: pre-line; font-size: 13px" >{{ poem.summary }}</p>
    <br> <br>
  <h5>{% if poem.genre.all.count > 1 %} Жанри вірша:
      {% else %} Жанр вірша: {% endif %}  </h5>
  {% for genre in poem.genre.all %}
  <a href="{{ genre.get_absolute_url }}"> <b> {{ genre.name }} </b></a>
      <br>
  {% endfor %}

  <h5>{% if poem.book.all.count > 1 %} Книги вірша:
      {% else %} Книга вірша: {% endif %}  </h5>
  {% for book in poem.book.all %}
    <a href="{{ book.get_absolute_url }}"> <b> {{ book.title }} </b></a>
      <br>
  {% endfor %}
      <br>
  {% if poem.image_poem %}
    <a href="{% url 'poems:poem-collage' poem.id %}"> <b> Колаж вірша </b>
                           <b style= "color: red">&{{symbol_collage}};</b></a>
  {% endif %}

      <br>
      <br>

    {% endblock %}

</div>   <!-- poem_detail -->


<div class="side_right_tytle">
        {% if art_image %}
<table style="width: 100.0%">
<tr>
<td> <img src="{% static art_image %}" alt="{{ book.name_book }}"
          style="width:97.0%" /> </td>
</tr>
</table>
        {% endif %}
        {% if list_name %}
            <p style = "font-size: 16px"> <b>{{list_name}}</b> </p>
        {% endif %}


</div>  <!-- side_right_tytle -->

<div class="side_right_poem">
{% for poem in poem_list %}
    {% if art == "book" %}
   <li>
   <a href="{% url 'poems:poem-book' poem.id art_id %}">
       <b style = "line-height: 0.5; font-size: 12px"> {{ poem.tytle }}</b></a><br>
   </li>
    {% endif %}

    {% if art == "genre" %}
   <li>
   <a href="{% url 'poems:poem-genre' poem.id art_id %}">
       <b style = "line-height: 0.5; font-size: 12px"> {{ poem.tytle }}</b></a><br>
   </li>
    {% endif %}

    {% if art == "lang" %}
   <li>
   <a href="{% url 'poems:poem-lang' poem.id art_id %}">
       <b style = "line-height: 0.5; font-size: 12px"> {{ poem.tytle }}</b></a><br>
   </li>
    {% endif %}

{% endfor %}
</div> <!-- side_right_poem -->

{% endblock %}



</body>
</html>